### ISSUE TITLE
What the fuck is Jai?

### ISSUE THREAD

**Issue by h4rldev** [ArjixWasTaken/rai#1]
You mean the language?

**Comment by ArjixWasTaken** [comment]
If you spent some time reading the readme, I think it would be obvious.

**Comment by h4rldev** [comment]
Rai

Jai made in Rust, well, at least thats the goal :^)
Why?

Since Jai is a closed-beta, and will continue to be for the foreseeable future, I decided to make a clone of it in Rust. I'm not sure if I'll ever finish it, but I'm having fun making it, so why not?
🚧 Progress 🚧

    Lexer // well, kinda
    Parser
    Type Checker
    Interpreter
    Codegen (to C++)

Q/A

Q: Will this be a 1:1 clone of Jai?
A: While that is the goal, I'm not sure that I can compete with the Jai team... so I'll probably just make a subset of Jai.

Q: Why Rust?
A: 🦀🦀
You got more questions? Ask them in the issues tab!


Doesn't seem to show anything

**Comment by ArjixWasTaken** [comment]
dunno about you, but 

```
Lexer // well, kinda
Parser
Type Checker
Interpreter
Codegen (to C++)
```

obviously indicates that this is about a language

and also

```
Q: Will this be a 1:1 clone of Jai?
A: While that is the goal, I'm not sure that I can compete with the Jai team... so I'll probably just make a subset of Jai.
```

*subset of Jai*, I don't see the word subset used for stuff that is not about an array
in this case an array of features

**Comment by ArjixWasTaken** [comment]
could I have responded in a kinder way? yes
but I smelled a shitpost when I read this issue title

**Comment by ArjixWasTaken** [comment]
even if you know nothing about Jai and you dont find the readme informative enough to understand it is about the language, a simple google search for "Jai closed beta" would answer your question

![image](https://user-images.githubusercontent.com/53124886/232741916-2498bcb8-57bf-470c-aba7-1f9879b72a8c.png)

**Comment by ArjixWasTaken** [comment]
PS: I'm sorry for being aggressive.
